/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTree: typeof import('element-plus/es')['ElTree']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    Logo: typeof import('./../components/Logo.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTree: typeof import('naive-ui')['NTree']
    PageHeader: typeof import('./../components/PageHeader.vue')['default']
  }
}
